[package]
name = "maid-sandbox"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
maid-core = { path = "../core" }
shell-words.workspace = true
tokio.workspace = true
tracing.workspace = true
